name: beaute_naturelle
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  http: ^1.5.0
  provider: ^6.1.5+1
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^6.0.0
  flutter_facebook_auth: ^6.0.5
  lottie: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.7
  image_picker: ^1.1.1
  flutter_animate: ^4.5.0
  image_cropper: ^11.0.0
  permission_handler: ^11.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo2.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo2.png"

flutter:
  uses-material-design: true
  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf

  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/vector.svg
    - assets/vector-1.svg
    - assets/vector-2.svg
    - assets/vector-3.svg
    - assets/vector-4.svg
    - assets/vector-5.svg
    - assets/images/photo-filles.jpg
    - assets/images/allergie.jpg
    - assets/images/aloevera2.jpg
    - assets/images/aloevera1.jpg
    - assets/images/icone-coeur.svg
    - assets/images/icone-home.svg
    - assets/images/icone-menu.svg
    - assets/images/icone-passport.svg
    - assets/images/icone-profil.svg
    - assets/images/icone-recette.svg
    - assets/images/oip.jpg
    - assets/images/recette/aloe_vera.jpg
    - assets/images/recette/amande.jpg
    - assets/images/recette/argan.jpg
    - assets/images/recette/concombre.jpg
    - assets/images/recette/curcuma.jpg
    - assets/images/recette/riz.jpg
